### ISSUE TITLE
Documentation toolchain enhancements

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon-build-tools#842]
For Helidon 4 we are planing to enhance the documentation toolchain.

- [ ] Search engine optimized (SEO)
- [ ] Table of Contents support
- [ ] Tabbed source snippets
- [ ] Continue to use asciidoc as authoring language
